# Generated by Django 4.0.4 on 2022-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners/')),
                ('name', models.CharField(max_length=128)),
                ('social', models.CharField(max_length=256)),
            ],
        ),
    ]
